// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_board_ from "./routes/[board].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_login_anonymous from "./routes/api/login/anonymous.ts";
import * as $api_login_google from "./routes/api/login/google.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_new_board from "./routes/api/new_board.tsx";
import * as $api_remove_user_from_board from "./routes/api/remove_user_from_board.tsx";
import * as $api_rename_board from "./routes/api/rename_board.tsx";
import * as $api_set_name from "./routes/api/set_name.ts";
import * as $index from "./routes/index.tsx";
import * as $set_name from "./routes/set_name.tsx";
import * as $app_BoardTileToolbar from "./islands/app/BoardTileToolbar.tsx";
import * as $app_DashboardMenu from "./islands/app/DashboardMenu.tsx";
import * as $app_IconCircle from "./islands/app/IconCircle.tsx";
import * as $app_LoginForm from "./islands/app/LoginForm.tsx";
import * as $app_Reload from "./islands/app/Reload.tsx";
import * as $app_SetName from "./islands/app/SetName.tsx";
import * as $app_ThemeSelector from "./islands/app/ThemeSelector.tsx";
import * as $app_Themed from "./islands/app/Themed.tsx";
import * as $app_WithClient from "./islands/app/WithClient.tsx";
import * as $board_AccountMenu from "./islands/board/AccountMenu.tsx";
import * as $board_Board from "./islands/board/Board.tsx";
import * as $board_CameraView from "./islands/board/CameraView.tsx";
import * as $board_ColorSelector from "./islands/board/ColorSelector.tsx";
import * as $board_CursorBox from "./islands/board/CursorBox.tsx";
import * as $board_DrawableCanvas from "./islands/board/DrawableCanvas.tsx";
import * as $board_MouseTracker from "./islands/board/MouseTracker.tsx";
import * as $board_ObservableCanvas from "./islands/board/ObservableCanvas.tsx";
import * as $board_SizeSelector from "./islands/board/SizeSelector.tsx";
import * as $board_StylusModeSelector from "./islands/board/StylusModeSelector.tsx";
import * as $board_ToolSelector from "./islands/board/ToolSelector.tsx";
import * as $board_Toolbar from "./islands/board/Toolbar.tsx";
import * as $board_webgl_utils_constants from "./islands/board/webgl-utils/constants.ts";
import * as $board_webgl_utils_index from "./islands/board/webgl-utils/index.ts";
import * as $board_webgl_utils_line_drawing from "./islands/board/webgl-utils/line_drawing.ts";
import * as $board_webgl_utils_utils from "./islands/board/webgl-utils/utils.ts";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[board].tsx": $_board_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/login/anonymous.ts": $api_login_anonymous,
    "./routes/api/login/google.ts": $api_login_google,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/new_board.tsx": $api_new_board,
    "./routes/api/remove_user_from_board.tsx": $api_remove_user_from_board,
    "./routes/api/rename_board.tsx": $api_rename_board,
    "./routes/api/set_name.ts": $api_set_name,
    "./routes/index.tsx": $index,
    "./routes/set_name.tsx": $set_name,
  },
  islands: {
    "./islands/app/BoardTileToolbar.tsx": $app_BoardTileToolbar,
    "./islands/app/DashboardMenu.tsx": $app_DashboardMenu,
    "./islands/app/IconCircle.tsx": $app_IconCircle,
    "./islands/app/LoginForm.tsx": $app_LoginForm,
    "./islands/app/Reload.tsx": $app_Reload,
    "./islands/app/SetName.tsx": $app_SetName,
    "./islands/app/ThemeSelector.tsx": $app_ThemeSelector,
    "./islands/app/Themed.tsx": $app_Themed,
    "./islands/app/WithClient.tsx": $app_WithClient,
    "./islands/board/AccountMenu.tsx": $board_AccountMenu,
    "./islands/board/Board.tsx": $board_Board,
    "./islands/board/CameraView.tsx": $board_CameraView,
    "./islands/board/ColorSelector.tsx": $board_ColorSelector,
    "./islands/board/CursorBox.tsx": $board_CursorBox,
    "./islands/board/DrawableCanvas.tsx": $board_DrawableCanvas,
    "./islands/board/MouseTracker.tsx": $board_MouseTracker,
    "./islands/board/ObservableCanvas.tsx": $board_ObservableCanvas,
    "./islands/board/SizeSelector.tsx": $board_SizeSelector,
    "./islands/board/StylusModeSelector.tsx": $board_StylusModeSelector,
    "./islands/board/ToolSelector.tsx": $board_ToolSelector,
    "./islands/board/Toolbar.tsx": $board_Toolbar,
    "./islands/board/webgl-utils/constants.ts": $board_webgl_utils_constants,
    "./islands/board/webgl-utils/index.ts": $board_webgl_utils_index,
    "./islands/board/webgl-utils/line_drawing.ts":
      $board_webgl_utils_line_drawing,
    "./islands/board/webgl-utils/utils.ts": $board_webgl_utils_utils,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
