// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $Canvas from "./islands/Canvas.tsx";
import * as $ClientList from "./islands/ClientList.tsx";
import * as $CursorBox from "./islands/CursorBox.tsx";
import * as $MouseTracker from "./islands/MouseTracker.tsx";
import * as $PingButton from "./islands/PingButton.tsx";
import * as $WithClient from "./islands/WithClient.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Canvas.tsx": $Canvas,
    "./islands/ClientList.tsx": $ClientList,
    "./islands/CursorBox.tsx": $CursorBox,
    "./islands/MouseTracker.tsx": $MouseTracker,
    "./islands/PingButton.tsx": $PingButton,
    "./islands/WithClient.tsx": $WithClient,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
